#!/usr/bin/env python3
"""Check customer-facing repository structure and text hygiene."""

from __future__ import annotations

import re
import sys
from pathlib import Path


EXAMPLE_ROOT = Path("examples/esp-idf")
BAD_TEXT_PATTERNS = (
    (
        "stale ESP32-P4 Function EV Board text",
        re.compile(r"ESP32[-_ ]P4[-_ ]Function[-_ ]EV[-_ ]Board", re.IGNORECASE),
    ),
    ("stale ESP32-S3 LCD EV board text", re.compile(r"ESP32_S3_LCD_EV_BOARD", re.IGNORECASE)),
    ("stale esp-dev-kits text", re.compile(r"esp-dev-kits", re.IGNORECASE)),
    ("garbled replacement characters", re.compile(r"\ufffd")),
    ("Windows drive-local path", re.compile(r"\b[A-Za-z]:\\")),
    ("UNC or network-share path", re.compile(r"\\\\[^\\\s]+\\[^\\\s]+")),
    ("host-local user path", re.compile(r"/(?:Users|home)/[^/\s]+")),
    (
        "automation provenance text",
        re.compile(
            r"\b(?:codex|chatgpt|llm|gpt[-_ ]?(?:3|4|5|o)|ai-generated|generated by ai)\b",
            re.IGNORECASE,
        ),
    ),
)
PUBLIC_TEXT_SUFFIXES = {
    ".md",
    ".yaml",
    ".yml",
}
GENERATED_FILENAMES = {
    "sdkconfig",
    "sdkconfig.old",
    "dependencies.lock",
}
GENERATED_DIRECTORIES = {
    "build",
    "build-local",
    "managed_components",
}


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)


def list_public_text_files() -> list[Path]:
    return sorted(
        Path(filename)
        for filename in git_ls_files()
        if Path(filename).suffix.lower() in PUBLIC_TEXT_SUFFIXES
        and Path(filename).is_file()
    )


def git_ls_files() -> list[str]:
    import subprocess

    result = subprocess.run(
        ["git", "ls-files"],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return [line for line in result.stdout.splitlines() if line]


def check_example_root() -> int:
    errors = 0
    if not EXAMPLE_ROOT.is_dir():
        fail(f"missing {EXAMPLE_ROOT.as_posix()}")
        return 1

    examples_dir = Path("examples")
    seen_names: dict[str, Path] = {}
    for path in examples_dir.iterdir():
        if not path.is_dir():
            continue
        key = path.name.lower()
        if key in seen_names:
            fail(
                "case-insensitive duplicate under examples/: "
                f"{seen_names[key].as_posix()} and {path.as_posix()}"
            )
            errors += 1
        seen_names[key] = path

    if seen_names.get("esp-idf") != EXAMPLE_ROOT:
        fail("use examples/esp-idf for ESP-IDF examples")
        errors += 1

    numbers: dict[str, Path] = {}
    for path in sorted(p for p in EXAMPLE_ROOT.iterdir() if p.is_dir()):
        match = re.match(r"^(\d{2})_", path.name)
        if not match:
            fail(f"example directory lacks NN_ prefix: {path.as_posix()}")
            errors += 1
            continue
        if path.name != path.name.lower():
            fail(f"example directory must be lowercase: {path.as_posix()}")
            errors += 1

        prefix = match.group(1)
        if prefix in numbers:
            fail(
                "duplicate example numeric prefix "
                f"{prefix}: {numbers[prefix].as_posix()} and {path.as_posix()}"
            )
            errors += 1
        numbers[prefix] = path

        if not (path / "README.md").is_file():
            fail(f"missing customer README.md: {path.as_posix()}")
            errors += 1

    return errors


def check_public_text() -> int:
    errors = 0
    for path in list_public_text_files():
        text = path.read_text(encoding="utf-8")
        for label, pattern in BAD_TEXT_PATTERNS:
            if pattern.search(text):
                fail(f"{path.as_posix()} contains {label}")
                errors += 1
    return errors


def check_markdown_links() -> int:
    errors = 0
    link_re = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
    for path in list_public_text_files():
        if path.suffix.lower() != ".md":
            continue
        text = path.read_text(encoding="utf-8")
        for raw_target in link_re.findall(text):
            target = raw_target.strip()
            if (
                not target
                or target.startswith("#")
                or re.match(r"^[a-z][a-z0-9+.-]*:", target, flags=re.IGNORECASE)
            ):
                continue
            target = target.split("#", 1)[0].strip()
            if not target:
                continue
            if target.startswith("<") and target.endswith(">"):
                target = target[1:-1]
            candidate = (path.parent / target).resolve()
            if not candidate.exists():
                fail(f"{path.as_posix()} has broken local link: {raw_target}")
                errors += 1
    return errors


def check_generated_outputs() -> int:
    errors = 0
    try:
        tracked = Path(".").joinpath(".git").exists()
        if not tracked:
            return errors
        filenames = git_ls_files()
    except Exception as exc:  # pragma: no cover - best-effort local helper
        fail(f"unable to list tracked files: {exc}")
        return 1

    for filename in filenames:
        normalized = filename.replace("\\", "/")
        parts = normalized.split("/")
        basename = parts[-1]
        if basename in GENERATED_FILENAMES or any(
            part in GENERATED_DIRECTORIES for part in parts[:-1]
        ):
            fail(f"generated ESP-IDF output is tracked: {filename}")
            errors += 1
    return errors


def check_case_insensitive_tracked_paths() -> int:
    errors = 0
    try:
        filenames = git_ls_files()
    except Exception as exc:  # pragma: no cover - best-effort local helper
        fail(f"unable to list tracked files: {exc}")
        return 1

    seen: dict[str, str] = {}
    for filename in filenames:
        key = filename.replace("\\", "/").lower()
        if key in seen and seen[key] != filename:
            fail(f"case-insensitive duplicate tracked paths: {seen[key]} and {filename}")
            errors += 1
            continue
        seen[key] = filename

    return errors


def main() -> int:
    errors = 0
    errors += check_example_root()
    errors += check_public_text()
    errors += check_markdown_links()
    errors += check_generated_outputs()
    errors += check_case_insensitive_tracked_paths()

    if errors:
        fail(f"public repository check failed with {errors} issue(s)")
        return 1

    print("Public repository checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
